name: Deploy to VPS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_DEPLOY_KEY }}

    - name: Add VPS host to known_hosts
      run: |
        ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

    - name: Clean VPS directory Except the .env file and storage
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} "rm -rf ${{ secrets.VPS_APP_DIR }}/node_modules; rm -rf ${{ secrets.VPS_APP_DIR }}/public; rm -rf ${{ secrets.VPS_APP_DIR }}/vendor; find ${{ secrets.VPS_APP_DIR }} -mindepth 1 -maxdepth 1 -not -name '.env' -not -name 'storage' -exec rm -rf {} +"

    - name: Copy files to VPS
      run: |
        rsync -avz --delete --exclude '.env' --exclude 'storage' -e "ssh -p ${{ secrets.VPS_PORT }}" ./ ${{ secrets.VPS_HOST }}:${{ secrets.VPS_APP_DIR }}/

    - name: Install composer dependencies
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} "cd ${{ secrets.VPS_APP_DIR }} && /opt/alt/php-fpm73/usr/bin/php /opt/composer/composer install --no-dev --optimize-autoloader"

    - name: Run migrations
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} "cd ${{ secrets.VPS_APP_DIR }} && /opt/alt/php-fpm73/usr/bin/php artisan migrate --force"

    - name: Clear cache and settings
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} "cd ${{ secrets.VPS_APP_DIR }} && /opt/alt/php-fpm73/usr/bin/php artisan config:cache; /opt/alt/php-fpm73/usr/bin/php artisan route:cache; /opt/alt/php-fpm73/usr/bin/php artisan view:cache; /opt/alt/php-fpm73/usr/bin/php artisan optimize:clear"

    - name: Create Link Simbolic Storage
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} "cd ${{ secrets.VPS_APP_DIR }} && /opt/alt/php-fpm73/usr/bin/php artisan storage:link"
